---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubantu-20.04
    steps:
      - name: LOgin to Docker Hub
        uses: docker/login=actin@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"  
